include: package:lints/recommended.yaml

analyzer:
  exclude:
    # Ignore generated files
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
    - "**/example/**"
    - "**/*test.dart"
