name: usedesk
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  pigeon: ^1.0.18

dependency_overrides:
  # analyzer: ^3.3.1
  analyzer: ^2.4.0

flutter:
  plugin:
    platforms:
      android:
        package: ru.usedesk.usedesk
        pluginClass: UsedeskPlugin
      ios:
        pluginClass: UsedeskPlugin
