name: usedesk
description: Pure dart SDK implementation of usedesk.com service
repository: https://github.com/ScerIO/usedesk.dart
issue_tracker: https://github.com/ScerIO/usedesk.dart/issues
version: 0.3.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  mime: ^1.0.1
  http: ^0.13.4
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^1.0.1
  build_runner: ^2.1.2
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  analyzer: '>=3.0.0 <3.3.0'
